name: Evaluar periodos

on:
  workflow_dispatch:

jobs:
  fetch_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install python-dateutil
      
      - name: Validate and adjust n_eval_periodos
        run: |
          python validate_eval_periodos.py
          
      - name: Read updated parameters
        run: |
          cat param.json
          echo "model_periodo=$(jq -r '.model_periodo' param.json)" >> $GITHUB_ENV
          echo "n_eval_periodos=$(jq -r '.n_eval_periodos' param.json)" >> $GITHUB_ENV
          echo "ult_periodo_data=$(jq -r '.ult_periodo_data' param.json)" >> $GITHUB_ENV
          
          echo "Parameters after validation:"
          echo "  model_periodo: $(jq -r '.model_periodo' param.json)"
          echo "  n_eval_periodos: $(jq -r '.n_eval_periodos' param.json)"
          echo "  ult_periodo_data: $(jq -r '.ult_periodo_data' param.json)"

      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.10'

      # - name: Install dependencies
      #   run: |
      #     pip install -r requirements.txt
      #     pip install azure-ai-ml azure-identity

      # - name: Azure Login
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Run Pipeline Script
      #   run: python fetch_version.py