name: Azure Pipeline Dev

on:
  workflow_dispatch:

jobs:
  fetch_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: read param.json and save values in variables
        run: |
          cat param.json
          echo "model_periodo=${{fromJson(steps.read_param.outputs.param).model_periodo}}" >> $GITHUB_ENV
          echo "n_eval_periodos=${{fromJson(steps.read_param.outputs.param).n_eval_periodos}}" >> $GITHUB_ENV
          echo "ult_periodo=${{fromJson(steps.read_param.outputs.param).ult_periodo}}" >> $GITHUB_ENV

      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.10'

      # - name: Install dependencies
      #   run: |
      #     pip install -r requirements.txt
      #     pip install azure-ai-ml azure-identity

      # - name: Azure Login
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Run Pipeline Script
      #   run: python fetch_version.py