name: Run Pipeline ML Inicial Regular

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install azure-ai-ml azure-identity
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Azure ML CLI extension
      run: |
          az extension add -n ml -y || az extension update -n ml
          az configure --defaults workspace=${{ fromJson(secrets.AZURE_CREDENTIALS).workspaceName }} group=${{ fromJson(secrets.AZURE_CREDENTIALS).resourceGroup}}

    - name: Submit diabetes pipeline job (no stream)
      env:
        AZURE_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
        AZURE_RESOURCE_GROUP: ${{ fromJson(secrets.AZURE_CREDENTIALS).resourceGroup }}
        AZURE_WORKSPACE_NAME: ${{ fromJson(secrets.AZURE_CREDENTIALS).workspaceName }}
      run: |
          JOB_ID=$(az ml job create \
            --file pl_ml_predict.yml \
            --query name -o tsv)

          echo "Submitted job: $JOB_ID"

    - name: Print Custom Pipeline Outputs
      run: |
          
          # Ahora consultamos los outputs especÃ­ficos definidos en tu YAML
          echo "--- Resultados del Pipeline ---"
          
          # 1. Output del Modelo Inicial
          model_inicial=$(az ml job show --name $JOB_ID --query outputs.output_model_inicial_version.path -o tsv)
          echo "Modelo Inicial guardado en: $model_inicial"
          
          # 2. Output del Target Continuidad
          target_path=$(az ml job show --name $JOB_ID --query outputs.output_target_continuidad_datastore.path -o tsv)
          echo "Target Continuidad en: $target_path"
        

    # - name: Run Pipeline Script
    #   env:
    #     AZURE_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
    #     AZURE_RESOURCE_GROUP: ${{ fromJson(secrets.AZURE_CREDENTIALS).resourceGroup }}
    #     AZURE_WORKSPACE_NAME: ${{ fromJson(secrets.AZURE_CREDENTIALS).workspaceName }}
    #   run: |
    #     python pipeline_cloud_base_v2_actions.py
    #  opcional: exponerlo como output del step
         # echo "job_id=$JOB_ID" >> $GITHUB_OUTPUT