name: Deploy Pipeline ML prod

on:
  # workflow_dispatch:
  workflow_call:
    inputs:
      platinum_version:
        required: true
        type: string
      feats_version:
        required: true
        type: string
      target_version:
        required: true
        type: string
      model_version:
        required: true
        type: string
      model_periodo:
        required: true
        type: number
      ult_periodo_data:
        required: true
        type: number
      n_eval_periodos:
        required: true
        type: number
  # push:
  #   branches:
  #     - prod

jobs:
  deploy-pl-ml-prod:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install azure-ai-ml azure-identity
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Azure ML CLI extension
      run: |
          az extension add -n ml -y || az extension update -n ml
          az configure --defaults workspace=${{ fromJson(secrets.AZURE_CREDENTIALS).workspaceName }} group=${{ fromJson(secrets.AZURE_CREDENTIALS).resourceGroup}}

    - name: Submit pipeline job and print outputs
      env:
        AZURE_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
        AZURE_RESOURCE_GROUP: ${{ fromJson(secrets.AZURE_CREDENTIALS).resourceGroup }}
        AZURE_WORKSPACE_NAME: ${{ fromJson(secrets.AZURE_CREDENTIALS).workspaceName }}
      run: |

          # Submit job with parameters from workflow inputs
          JOB_ID=$(az ml job create \
            --file pl_ml_predict_prod.yml \
            --set jobs.etl_job.inputs.platinum_version="${{ inputs.platinum_version }}" \
            --set jobs.etl_job.inputs.ult_periodo="${{ inputs.ult_periodo_data }}" \
            --set jobs.features_inicial_job.inputs.platinum_version="${{ inputs.platinum_version }}" \
            --set jobs.features_inicial_job.inputs.feats_version="${{ inputs.feats_version }}" \
            --set jobs.features_inicial_job.inputs.target_version="${{ inputs.target_version }}" \
            --set jobs.features_inicial_job.inputs.model_periodo="${{ inputs.model_periodo }}" \
            --set jobs.features_inicial_job.inputs.ult_periodo="${{ inputs.ult_periodo_data }}" \
            --set jobs.features_inicial_job.inputs.n_eval_periodos="${{ inputs.n_eval_periodos }}" \
            --set jobs.features_continuidad_job.inputs.platinum_version="${{ inputs.platinum_version }}" \
            --set jobs.features_continuidad_job.inputs.feats_version="${{ inputs.feats_version }}" \
            --set jobs.features_continuidad_job.inputs.target_version="${{ inputs.target_version }}" \
            --set jobs.features_continuidad_job.inputs.model_periodo="${{ inputs.model_periodo }}" \
            --set jobs.features_continuidad_job.inputs.ult_periodo="${{ inputs.ult_periodo_data }}" \
            --set jobs.features_continuidad_job.inputs.n_eval_periodos="${{ inputs.n_eval_periodos }}" \
            --set jobs.features_continuidad_horario_job.inputs.platinum_version="${{ inputs.platinum_version }}" \
            --set jobs.features_continuidad_horario_job.inputs.feats_version="${{ inputs.feats_version }}" \
            --set jobs.features_continuidad_horario_job.inputs.target_version="${{ inputs.target_version }}" \
            --set jobs.features_continuidad_horario_job.inputs.model_periodo="${{ inputs.model_periodo }}" \
            --set jobs.features_continuidad_horario_job.inputs.ult_periodo="${{ inputs.ult_periodo_data }}" \
            --set jobs.features_continuidad_horario_job.inputs.n_eval_periodos="${{ inputs.n_eval_periodos }}" \
            --set jobs.model_predict_inicial_job.inputs.model_version="${{ inputs.model_version }}" \
            --set jobs.model_predict_inicial_job.inputs.feats_version="${{ inputs.feats_version }}" \
            --set jobs.model_predict_inicial_job.inputs.model_periodo="${{ inputs.model_periodo }}" \
            --set jobs.model_predict_inicial_job.inputs.n_eval_periodos="${{ inputs.n_eval_periodos }}" \
            --set jobs.model_predict_continuidad_job.inputs.model_version="${{ inputs.model_version }}" \
            --set jobs.model_predict_continuidad_job.inputs.feats_version="${{ inputs.feats_version }}" \
            --set jobs.model_predict_continuidad_job.inputs.model_periodo="${{ inputs.model_periodo }}" \
            --set jobs.model_predict_continuidad_job.inputs.n_eval_periodos="${{ inputs.n_eval_periodos }}" \
            --set jobs.model_predict_continuidad_horario_job.inputs.model_version="${{ inputs.model_version }}" \
            --set jobs.model_predict_continuidad_horario_job.inputs.feats_version="${{ inputs.feats_version }}" \
            --set jobs.model_predict_continuidad_horario_job.inputs.model_periodo="${{ inputs.model_periodo }}" \
            --set jobs.model_predict_continuidad_horario_job.inputs.n_eval_periodos="${{ inputs.n_eval_periodos }}" \
            --query name -o tsv)

          echo "Submitted job: $JOB_ID"

          # Wait for the job to complete
          # echo "Waiting for job to complete..."
          # az ml job stream --name $JOB_ID
          