name: Run Pipeline Base

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      mode:
        required: true
        type: string
      model_periodo:
        required: true
        type: number
      ult_periodo_data:
        required: true
        type: number
      n_eval_periodos:
        required: true
        type: number
      periodo:
        required: true
        type: number
      with_tipo:
        required: true
        type: string
      platinum_version:
        required: true
        type: string
      feats_version:
        required: true
        type: string
      target_version:
        required: true
        type: string
      model_version:
        required: true
        type: string
    outputs:
      response_inicial:
        description: "Evaluation response for inicial_regular"
        value: ${{ jobs.run-pipeline.outputs.response_inicial }}
      response_continuidad_horario:
        description: "Evaluation response for continuidad_regular_horario"
        value: ${{ jobs.run-pipeline.outputs.response_continuidad_horario }}
jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install azure-ai-ml azure-identity
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Azure ML CLI extension
      run: |
          az extension add -n ml -y || az extension update -n ml
          az configure --defaults workspace=${{ fromJson(secrets.AZURE_RESOURCES_DEV).workspaceName }} group=${{ fromJson(secrets.AZURE_RESOURCES_DEV).resourceGroup}}

    - name: Submit pipeline job and print outputs
      id: submit_job
      # env:
      #   AZURE_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
      #   AZURE_RESOURCE_GROUP: ${{ fromJson(secrets.AZURE_RESOURCES_DEV).resourceGroup }}
      #   AZURE_WORKSPACE_NAME: ${{ fromJson(secrets.AZURE_RESOURCES_DEV).workspaceName }}
      run: |
          # Submit job with only the provided parameters
          # JOB_ID=$(az ml job create \
          #   --file pl_ml_deploy_evaluate.yml \
          #   --query name -o tsv)

          JOB_ID=$(az ml job create \
            --file pl_ml_deploy_evaluate.yml \
            --set jobs.etl_job.inputs.platinum_version="${{ inputs.platinum_version }}" \
            --set jobs.etl_job.inputs.ult_periodo="${{ inputs.ult_periodo_data }}" \
            --set jobs.features_inicial_job.inputs.platinum_version="${{ inputs.platinum_version }}" \
            --set jobs.features_inicial_job.inputs.feats_version="${{ inputs.feats_version }}" \
            --set jobs.features_inicial_job.inputs.target_version="${{ inputs.target_version }}" \
            --set jobs.features_inicial_job.inputs.model_periodo="${{ inputs.model_periodo }}" \
            --set jobs.features_inicial_job.inputs.ult_periodo="${{ inputs.ult_periodo_data }}" \
            --set jobs.features_inicial_job.inputs.n_eval_periodos="${{ inputs.n_eval_periodos }}" \
            --set jobs.features_inicial_job.inputs.periodo="${{ inputs.periodo }}" \
            --set jobs.features_inicial_job.inputs.mode="${{ inputs.mode }}" \
            --set jobs.features_inicial_job.inputs.with_tipo="${{ inputs.with_tipo }}" \
            --set jobs.features_continuidad_job.inputs.platinum_version="${{ inputs.platinum_version }}" \
            --set jobs.features_continuidad_job.inputs.feats_version="${{ inputs.feats_version }}" \
            --set jobs.features_continuidad_job.inputs.target_version="${{ inputs.target_version }}" \
            --set jobs.features_continuidad_job.inputs.model_periodo="${{ inputs.model_periodo }}" \
            --set jobs.features_continuidad_job.inputs.ult_periodo="${{ inputs.ult_periodo_data }}" \
            --set jobs.features_continuidad_job.inputs.n_eval_periodos="${{ inputs.n_eval_periodos }}" \
            --set jobs.features_continuidad_job.inputs.periodo="${{ inputs.periodo }}" \
            --set jobs.features_continuidad_job.inputs.mode="${{ inputs.mode }}" \
            --set jobs.features_continuidad_job.inputs.with_tipo="${{ inputs.with_tipo }}" \
            --set jobs.features_continuidad_horario_job.inputs.platinum_version="${{ inputs.platinum_version }}" \
            --set jobs.features_continuidad_horario_job.inputs.feats_version="${{ inputs.feats_version }}" \
            --set jobs.features_continuidad_horario_job.inputs.target_version="${{ inputs.target_version }}" \
            --set jobs.features_continuidad_horario_job.inputs.model_periodo="${{ inputs.model_periodo }}" \
            --set jobs.features_continuidad_horario_job.inputs.ult_periodo="${{ inputs.ult_periodo_data }}" \
            --set jobs.features_continuidad_horario_job.inputs.n_eval_periodos="${{ inputs.n_eval_periodos }}" \
            --set jobs.features_continuidad_horario_job.inputs.periodo="${{ inputs.periodo }}" \
            --set jobs.features_continuidad_horario_job.inputs.mode="${{ inputs.mode }}" \
            --set jobs.features_continuidad_horario_job.inputs.with_tipo="${{ inputs.with_tipo }}" \
            --set jobs.model_predict_inicial_job.inputs.model_version="${{ inputs.model_version }}" \
            --set jobs.model_predict_inicial_job.inputs.feats_version="${{ inputs.feats_version }}" \
            --set jobs.model_predict_inicial_job.inputs.model_periodo="${{ inputs.model_periodo }}" \
            --set jobs.model_predict_inicial_job.inputs.n_eval_periodos="${{ inputs.n_eval_periodos }}" \
            --set jobs.model_predict_inicial_job.inputs.periodo="${{ inputs.periodo }}" \
            --set jobs.model_predict_inicial_job.inputs.mode="${{ inputs.mode }}" \
            --set jobs.model_predict_inicial_job.inputs.with_tipo="${{ inputs.with_tipo }}" \
            --set jobs.model_predict_continuidad_job.inputs.model_version="${{ inputs.model_version }}" \
            --set jobs.model_predict_continuidad_job.inputs.feats_version="${{ inputs.feats_version }}" \
            --set jobs.model_predict_continuidad_job.inputs.model_periodo="${{ inputs.model_periodo }}" \
            --set jobs.model_predict_continuidad_job.inputs.n_eval_periodos="${{ inputs.n_eval_periodos }}" \
            --set jobs.model_predict_continuidad_job.inputs.periodo="${{ inputs.periodo }}" \
            --set jobs.model_predict_continuidad_job.inputs.mode="${{ inputs.mode }}" \
            --set jobs.model_predict_continuidad_job.inputs.with_tipo="${{ inputs.with_tipo }}" \
            --set jobs.model_predict_continuidad_horario_job.inputs.model_version="${{ inputs.model_version }}" \
            --set jobs.model_predict_continuidad_horario_job.inputs.feats_version="${{ inputs.feats_version }}" \
            --set jobs.model_predict_continuidad_horario_job.inputs.model_periodo="${{ inputs.model_periodo }}" \
            --set jobs.model_predict_continuidad_horario_job.inputs.n_eval_periodos="${{ inputs.n_eval_periodos }}" \
            --set jobs.model_predict_continuidad_horario_job.inputs.periodo="${{ inputs.periodo }}" \
            --set jobs.model_predict_continuidad_horario_job.inputs.mode="${{ inputs.mode }}" \
            --set jobs.model_predict_continuidad_horario_job.inputs.with_tipo="${{ inputs.with_tipo }}" \
            --set jobs.model_evaluation_inicial_job.inputs.target_version="${{ inputs.target_version }}" \
            --set jobs.model_evaluation_inicial_job.inputs.model_periodo="${{ inputs.model_periodo }}" \
            --set jobs.model_evaluation_inicial_job.inputs.model_version="${{ inputs.model_version }}" \
            --set jobs.model_evaluation_inicial_job.inputs.n_eval_periodos="${{ inputs.n_eval_periodos }}" \
            --set jobs.model_evaluation_inicial_job.inputs.periodo="${{ inputs.periodo }}" \
            --set jobs.model_evaluation_inicial_job.inputs.mode="${{ inputs.mode }}" \
            --set jobs.model_evaluation_inicial_job.inputs.with_tipo="${{ inputs.with_tipo }}" \
            --set jobs.model_evaluation_continuidad_job.inputs.target_version="${{ inputs.target_version }}" \
            --set jobs.model_evaluation_continuidad_job.inputs.model_periodo="${{ inputs.model_periodo }}" \
            --set jobs.model_evaluation_continuidad_job.inputs.model_version="${{ inputs.model_version }}" \
            --set jobs.model_evaluation_continuidad_job.inputs.n_eval_periodos="${{ inputs.n_eval_periodos }}" \
            --set jobs.model_evaluation_continuidad_job.inputs.periodo="${{ inputs.periodo }}" \
            --set jobs.model_evaluation_continuidad_job.inputs.mode="${{ inputs.mode }}" \
            --set jobs.model_evaluation_continuidad_job.inputs.with_tipo="${{ inputs.with_tipo }}" \
            --set jobs.model_evaluation_continuidad_horario_job.inputs.target_version="${{ inputs.target_version }}" \
            --set jobs.model_evaluation_continuidad_horario_job.inputs.model_periodo="${{ inputs.model_periodo }}" \
            --set jobs.model_evaluation_continuidad_horario_job.inputs.model_version="${{ inputs.model_version }}" \
            --set jobs.model_evaluation_continuidad_horario_job.inputs.n_eval_periodos="${{ inputs.n_eval_periodos }}" \
            --set jobs.model_evaluation_continuidad_horario_job.inputs.periodo="${{ inputs.periodo }}" \
            --set jobs.model_evaluation_continuidad_horario_job.inputs.mode="${{ inputs.mode }}" \
            --set jobs.model_evaluation_continuidad_horario_job.inputs.with_tipo="${{ inputs.with_tipo }}" \
            --query name -o tsv)

          echo "Submitted job: $JOB_ID"

          # Wait for the job to complete
          # echo "Waiting for job to complete..."
          az ml job stream --name $JOB_ID
          # az ml job wait --name $JOB_ID

          CHILD_JOB_NAME_INICIAL=$(az ml job list --parent-job-name $JOB_ID --query "[?display_name=='model_evaluation_inicial_job'].name | [0]" -o tsv)
          CHILD_JOB_NAME_HORARIO=$(az ml job list --parent-job-name $JOB_ID --query "[?display_name=='model_evaluation_continuidad_horario_job'].name | [0]" -o tsv)

          echo "Submitted children job inicial: $CHILD_JOB_NAME_INICIAL"
          echo "Submitted children job horario: $CHILD_JOB_NAME_HORARIO"

          # az ml job show --name $CHILD_JOB_NAME_INICIAL

          az ml job download --name $CHILD_JOB_NAME_INICIAL --output-name output_evaluation_inicial_datastore --download-path ./outputs_metrics_inicial
          az ml job download --name $CHILD_JOB_NAME_HORARIO --output-name output_evaluation_continuidad_horario_datastore --download-path ./outputs_metrics_horario
          
          response_inicial_file=$(find ./outputs_metrics_inicial -name "response_*.txt" | head -n 1)
          response_continuidad_horario_file=$(find ./outputs_metrics_horario -name "response_*.txt" | head -n 1)
          
          if [ -f "$response_inicial_file" ]; then
              response_inicial=$(cat "$response_inicial_file")
              echo "El response obtenido desde archivo es: $response_inicial"
          else
              echo "Error: No se encontró el archivo response_inicial.txt"
              response_inicial="failed"
          fi
        
          if [ -f "$response_continuidad_horario_file" ]; then
              response_continuidad_horario=$(cat "$response_continuidad_horario_file")
              echo "El response obtenido desde archivo es: $response_continuidad_horario"
          else
              echo "Error: No se encontró el archivo response_continuidad_regular_horario.txt"
              response_continuidad_horario="failed"
          fi
          
          echo "response_inicial=$response_inicial" >> $GITHUB_OUTPUT
          echo "response_continuidad_horario=$response_continuidad_horario" >> $GITHUB_OUTPUT

          if [ "$response_inicial" == "failed" ] || [ "$response_continuidad_horario" == "failed" ]; then
              exit 1
          fi

    outputs:
      response_inicial: ${{ steps.submit_job.outputs.response_inicial }}
      response_continuidad_horario: ${{ steps.submit_job.outputs.response_continuidad_horario }}
        