name: Run Pipeline Base

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      mode:
        required: true
        type: string
      model_periodo:
        required: true
        type: number
      ult_periodo_data:
        required: true
        type: number
      n_eval_periodos:
        required: true
        type: number
      periodo:
        required: true
        type: number
      with_tipo:
        required: true
        type: string
      platinum_version:
        required: true
        type: string
      feats_version:
        required: true
        type: string
      target_version:
        required: true
        type: string
      model_version:
        required: true
        type: string
      model_current_version:
        required: true
        type: string
    
    outputs:
      response_compare:
        description: "Evaluation response for compare"
        value: ${{ jobs.run-pipeline.outputs.response_compare }}
jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install azure-ai-ml azure-identity
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Azure ML CLI extension
      run: |
          az extension add -n ml -y || az extension update -n ml
          az configure --defaults workspace=${{ fromJson(secrets.AZURE_CREDENTIALS).workspaceName }} group=${{ fromJson(secrets.AZURE_CREDENTIALS).resourceGroup}}

    - name: Submit pipeline job and print outputs
      id: submit_job
      env:
        AZURE_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
        AZURE_RESOURCE_GROUP: ${{ fromJson(secrets.AZURE_CREDENTIALS).resourceGroup }}
        AZURE_WORKSPACE_NAME: ${{ fromJson(secrets.AZURE_CREDENTIALS).workspaceName }}
      run: |
          # Submit job with only the provided parameters
          # JOB_ID=$(az ml job create \
          #   --file pl_ml_deploy_compare.yml \
          #   --query name -o tsv)

          JOB_ID=$(az ml job create \
            --file pl_ml_deploy_compare.yml \
            --set jobs.etl_job.inputs.platinum_version="${{ inputs.platinum_version }}" \
            --set jobs.etl_job.inputs.ult_periodo="${{ inputs.ult_periodo_data }}" \
            --set jobs.features_inicial_job.inputs.platinum_version="${{ inputs.platinum_version }}" \
            --set jobs.features_inicial_job.inputs.feats_version="${{ inputs.feats_version }}" \
            --set jobs.features_inicial_job.inputs.target_version="${{ inputs.target_version }}" \
            --set jobs.features_inicial_job.inputs.model_periodo="${{ inputs.model_periodo }}" \
            --set jobs.features_inicial_job.inputs.ult_periodo="${{ inputs.ult_periodo_data }}" \
            --set jobs.features_inicial_job.inputs.n_eval_periodos="${{ inputs.n_eval_periodos }}" \
            --set jobs.features_inicial_job.inputs.periodo="${{ inputs.periodo }}" \
            --set jobs.features_inicial_job.inputs.mode="${{ inputs.mode }}" \
            --set jobs.features_inicial_job.inputs.with_tipo="${{ inputs.with_tipo }}" \
            --set jobs.features_continuidad_job.inputs.platinum_version="${{ inputs.platinum_version }}" \
            --set jobs.features_continuidad_job.inputs.feats_version="${{ inputs.feats_version }}" \
            --set jobs.features_continuidad_job.inputs.target_version="${{ inputs.target_version }}" \
            --set jobs.features_continuidad_job.inputs.model_periodo="${{ inputs.model_periodo }}" \
            --set jobs.features_continuidad_job.inputs.ult_periodo="${{ inputs.ult_periodo_data }}" \
            --set jobs.features_continuidad_job.inputs.n_eval_periodos="${{ inputs.n_eval_periodos }}" \
            --set jobs.features_continuidad_job.inputs.periodo="${{ inputs.periodo }}" \
            --set jobs.features_continuidad_job.inputs.mode="${{ inputs.mode }}" \
            --set jobs.features_continuidad_job.inputs.with_tipo="${{ inputs.with_tipo }}" \
            --set jobs.features_continuidad_horario_job.inputs.platinum_version="${{ inputs.platinum_version }}" \
            --set jobs.features_continuidad_horario_job.inputs.feats_version="${{ inputs.feats_version }}" \
            --set jobs.features_continuidad_horario_job.inputs.target_version="${{ inputs.target_version }}" \
            --set jobs.features_continuidad_horario_job.inputs.model_periodo="${{ inputs.model_periodo }}" \
            --set jobs.features_continuidad_horario_job.inputs.ult_periodo="${{ inputs.ult_periodo_data }}" \
            --set jobs.features_continuidad_horario_job.inputs.n_eval_periodos="${{ inputs.n_eval_periodos }}" \
            --set jobs.features_continuidad_horario_job.inputs.periodo="${{ inputs.periodo }}" \
            --set jobs.features_continuidad_horario_job.inputs.mode="${{ inputs.mode }}" \
            --set jobs.features_continuidad_horario_job.inputs.with_tipo="${{ inputs.with_tipo }}" \
            --set jobs.model_train_inicial_job.inputs.feats_version="${{ inputs.feats_version }}" \
            --set jobs.model_train_inicial_job.inputs.model_periodo="${{ inputs.model_periodo }}" \
            --set jobs.model_train_inicial_job.inputs.model_version="${{ inputs.model_version }}" \
            --set jobs.model_train_inicial_job.inputs.mode="${{ inputs.mode }}" \
            --set jobs.model_train_inicial_job.inputs.with_tipo="${{ inputs.with_tipo }}" \
            --set jobs.model_train_continuidad_job.inputs.feats_version="${{ inputs.feats_version }}" \
            --set jobs.model_train_continuidad_job.inputs.model_periodo="${{ inputs.model_periodo }}" \
            --set jobs.model_train_continuidad_job.inputs.model_version="${{ inputs.model_version }}" \
            --set jobs.model_train_continuidad_job.inputs.mode="${{ inputs.mode }}" \
            --set jobs.model_train_continuidad_job.inputs.with_tipo="${{ inputs.with_tipo }}" \
            --set jobs.model_train_continuidad_horario_job.inputs.feats_version="${{ inputs.feats_version }}" \
            --set jobs.model_train_continuidad_horario_job.inputs.model_periodo="${{ inputs.model_periodo }}" \
            --set jobs.model_train_continuidad_horario_job.inputs.model_version="${{ inputs.model_version }}" \
            --set jobs.model_train_continuidad_horario_job.inputs.mode="${{ inputs.mode }}" \
            --set jobs.model_train_continuidad_horario_job.inputs.with_tipo="${{ inputs.with_tipo }}" \
            --set jobs.model_predict_inicial_job.inputs.model_version="${{ inputs.model_version }}" \
            --set jobs.model_predict_inicial_job.inputs.feats_version="${{ inputs.feats_version }}" \
            --set jobs.model_predict_inicial_job.inputs.model_periodo="${{ inputs.model_periodo }}" \
            --set jobs.model_predict_inicial_job.inputs.n_eval_periodos="${{ inputs.n_eval_periodos }}" \
            --set jobs.model_predict_inicial_job.inputs.periodo="${{ inputs.periodo }}" \
            --set jobs.model_predict_inicial_job.inputs.mode="${{ inputs.mode }}" \
            --set jobs.model_predict_inicial_job.inputs.with_tipo="${{ inputs.with_tipo }}" \
            --set jobs.model_predict_continuidad_job.inputs.model_version="${{ inputs.model_version }}" \
            --set jobs.model_predict_continuidad_job.inputs.feats_version="${{ inputs.feats_version }}" \
            --set jobs.model_predict_continuidad_job.inputs.model_periodo="${{ inputs.model_periodo }}" \
            --set jobs.model_predict_continuidad_job.inputs.n_eval_periodos="${{ inputs.n_eval_periodos }}" \
            --set jobs.model_predict_continuidad_job.inputs.periodo="${{ inputs.periodo }}" \
            --set jobs.model_predict_continuidad_job.inputs.mode="${{ inputs.mode }}" \
            --set jobs.model_predict_continuidad_job.inputs.with_tipo="${{ inputs.with_tipo }}" \
            --set jobs.model_predict_continuidad_horario_job.inputs.model_version="${{ inputs.model_version }}" \
            --set jobs.model_predict_continuidad_horario_job.inputs.feats_version="${{ inputs.feats_version }}" \
            --set jobs.model_predict_continuidad_horario_job.inputs.model_periodo="${{ inputs.model_periodo }}" \
            --set jobs.model_predict_continuidad_horario_job.inputs.n_eval_periodos="${{ inputs.n_eval_periodos }}" \
            --set jobs.model_predict_continuidad_horario_job.inputs.periodo="${{ inputs.periodo }}" \
            --set jobs.model_predict_continuidad_horario_job.inputs.mode="${{ inputs.mode }}" \
            --set jobs.model_predict_continuidad_horario_job.inputs.with_tipo="${{ inputs.with_tipo }}" \
            --set jobs.model_evaluation_inicial_job.inputs.target_version="${{ inputs.target_version }}" \
            --set jobs.model_evaluation_inicial_job.inputs.model_periodo="${{ inputs.model_periodo }}" \
            --set jobs.model_evaluation_inicial_job.inputs.model_version="${{ inputs.model_version }}" \
            --set jobs.model_evaluation_inicial_job.inputs.n_eval_periodos="${{ inputs.n_eval_periodos }}" \
            --set jobs.model_evaluation_inicial_job.inputs.periodo="${{ inputs.periodo }}" \
            --set jobs.model_evaluation_inicial_job.inputs.mode="${{ inputs.mode }}" \
            --set jobs.model_evaluation_inicial_job.inputs.with_tipo="${{ inputs.with_tipo }}" \
            --set jobs.model_evaluation_continuidad_job.inputs.target_version="${{ inputs.target_version }}" \
            --set jobs.model_evaluation_continuidad_job.inputs.model_periodo="${{ inputs.model_periodo }}" \
            --set jobs.model_evaluation_continuidad_job.inputs.model_version="${{ inputs.model_version }}" \
            --set jobs.model_evaluation_continuidad_job.inputs.n_eval_periodos="${{ inputs.n_eval_periodos }}" \
            --set jobs.model_evaluation_continuidad_job.inputs.periodo="${{ inputs.periodo }}" \
            --set jobs.model_evaluation_continuidad_job.inputs.mode="${{ inputs.mode }}" \
            --set jobs.model_evaluation_continuidad_job.inputs.with_tipo="${{ inputs.with_tipo }}" \
            --set jobs.model_evaluation_continuidad_horario_job.inputs.target_version="${{ inputs.target_version }}" \
            --set jobs.model_evaluation_continuidad_horario_job.inputs.model_periodo="${{ inputs.model_periodo }}" \
            --set jobs.model_evaluation_continuidad_horario_job.inputs.model_version="${{ inputs.model_version }}" \
            --set jobs.model_evaluation_continuidad_horario_job.inputs.n_eval_periodos="${{ inputs.n_eval_periodos }}" \
            --set jobs.model_evaluation_continuidad_horario_job.inputs.periodo="${{ inputs.periodo }}" \
            --set jobs.model_evaluation_continuidad_horario_job.inputs.mode="${{ inputs.mode }}" \
            --set jobs.model_evaluation_continuidad_horario_job.inputs.with_tipo="${{ inputs.with_tipo }}" \
            --set jobs.compare_job.inputs.n_eval_periodos="${{ inputs.n_eval_periodos }}" \
            --set jobs.compare_job.inputs.model_periodo="${{ inputs.model_periodo }}" \
            --set jobs.compare_job.inputs.model_current_version="${{ inputs.model_current_version }}" \
            --set jobs.compare_job.inputs.model_version="${{ inputs.model_version }}" \
            --set jobs.compare_job.inputs.periodo="${{ inputs.periodo }}" \
            --set jobs.compare_job.inputs.with_tipo="${{ inputs.with_tipo }}" \
            --query name -o tsv)

          echo "Submitted job: $JOB_ID"

          # Wait for the job to complete
          # echo "Waiting for job to complete..."
          az ml job stream --name $JOB_ID
          # az ml job wait --name $JOB_ID

          CHILD_JOB_NAME=$(az ml job list --parent-job-name $JOB_ID --query "[?display_name=='compare_job'].name | [0]" -o tsv)

          echo "Submitted children job: $CHILD_JOB_NAME"

          az ml job download --name $CHILD_JOB_NAME --output-name output_compare_datastore --download-path ./outputs_metrics_compare

          
          response_compare_file=$(find ./outputs_metrics_compare -name "response_*.txt" | head -n 1)
          
          if [ -f "$response_compare_file" ]; then
              response_compare=$(cat "$response_compare_file")
              echo "El response obtenido desde archivo es: $response_compare"
          else
              echo "Error: No se encontrÃ³ el archivo response_compare.txt"
              response_compare="failed"
          fi
          
          echo "response_compare=$response_compare" >> $GITHUB_OUTPUT

          if [ "$response_compare" == "failed" ]; then
              exit 1
          fi

    outputs:
      response_compare: ${{ steps.submit_job.outputs.response_compare }}
        